name: kma-test-job

services:
  nginx:
    image: nginx:alpine
    ports:
      - 8011:80
    volumes:
      - ./site:/app:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build:
      context: ./docker
      dockerfile: ./php.dockerfile
    volumes:
      - ./site:/app
    user: 1000:1000
    working_dir: /app
    environment:
      RABBIT_HOST: rabbit
      RABBIT_PORT: 5672
      RABBIT_USER: user
      RABBIT_PASS: pass
      MYSQL_HOST: db
      MYSQL_DBNAME: db
      MYSQL_USER: root
      MYSQL_PASS: test
      CLICK_HOST: clickhouse
      CLICK_DBNAME: db
      CLICK_PORT: 8123
      CLICK_USER: default
      CLICK_PASS: ''

  rabbit:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - 8012:15672

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8013:8080
    volumes:
      - ./swagger.yaml:/app/swagger.yaml:ro
    environment:
      SWAGGER_JSON: /app/swagger.yaml

  db:
    image: mariadb
    volumes:
      - ./docker/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: db

  adminer:
    image: adminer
    ports:
      - 8014:8080

  clickhouse:
    image: clickhouse/clickhouse-server:latest-alpine
    volumes:
      - ./docker/click-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 8015:8123




